//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIController.ABIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ABIService.IABIService")]
    public interface IABIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABIService/getName", ReplyAction="http://tempuri.org/IABIService/getNameResponse")]
        string getName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABIService/getName", ReplyAction="http://tempuri.org/IABIService/getNameResponse")]
        System.Threading.Tasks.Task<string> getNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABIService/getFirstname", ReplyAction="http://tempuri.org/IABIService/getFirstnameResponse")]
        string getFirstname();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IABIService/getFirstname", ReplyAction="http://tempuri.org/IABIService/getFirstnameResponse")]
        System.Threading.Tasks.Task<string> getFirstnameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IABIServiceChannel : ABIController.ABIService.IABIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ABIServiceClient : System.ServiceModel.ClientBase<ABIController.ABIService.IABIService>, ABIController.ABIService.IABIService {
        
        public ABIServiceClient() {
        }
        
        public ABIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ABIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getName() {
            return base.Channel.getName();
        }
        
        public System.Threading.Tasks.Task<string> getNameAsync() {
            return base.Channel.getNameAsync();
        }
        
        public string getFirstname() {
            return base.Channel.getFirstname();
        }
        
        public System.Threading.Tasks.Task<string> getFirstnameAsync() {
            return base.Channel.getFirstnameAsync();
        }
    }
}
